site_name: VIPSpot Documentation
site_url: https://coderrvrse.github.io/vipspot
site_description: Production-grade portfolio site with hardened contact pipeline

repo_name: CoderRvrse/vipspot
repo_url: https://github.com/CoderRvrse/vipspot

theme:
  name: material
  palette:
    - scheme: default
      primary: teal
      accent: teal
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode
    - scheme: slate
      primary: teal
      accent: teal
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top
    - search.highlight
    - search.share
    - content.code.copy

plugins:
  - search
  - mermaid2

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true
  - attr_list
  - md_in_html

nav:
  - Home: index.md
  - Configuration: configuration.md
  - API Reference: api.md
  - Deployment: deployment.md
  - Analytics: analytics.md
  - Contributing: contributing.md

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/CoderRvrse/vipspot
    - icon: fontawesome/solid/globe
      link: https://vipspot.net
  analytics:
    provider: google
    property: G-XXXXXXXXXX

copyright: Copyright &copy; 2025 VIPSpot · Built by Rvrse™