name: VIPSpot CI + Pages

on:
  push:
    branches: [ main ]
    paths:
      - "index.html"
      - "site/**"
      - "css/**"
      - "js/**"
      - ".github/workflows/ci-pages.yml"
  pull_request:
    branches: [ main ]
  workflow_dispatch:

concurrency:
  group: pages-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  verify:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Guard against problematic Unicode in JS
        run: |
          # Check using Node.js for reliable Unicode detection across platforms
          if node -e "
            const fs=require('fs');
            let found=false;
            for(const f of ['js/main.js','js/matrix-bg.js','js/tilt-tech.js']){
              const s=fs.readFileSync(f,'utf8');
              if(/[\u201C\u201D\u2018\u2019\u2013\u2014\u2026]/.test(s)){
                console.log(f+': Contains problematic Unicode');
                found=true;
              }
            }
            if(found) process.exit(1);
          "; then
            echo "✅ No problematic Unicode characters found in JS files"
          else
            echo "::error title=Problematic Unicode in JS::Replace smart quotes, em-dashes, ellipses with ASCII equivalents."
            exit 1
          fi
      - name: JS syntax validation
        run: |
          for jsfile in js/*.js; do
            echo "Checking syntax: $jsfile"
            node --check "$jsfile" || exit 1
          done
          echo "✅ All JS files have valid syntax"
      - name: Guard against legacy RAF handle
        shell: bash
        run: |
          set -euo pipefail

          echo "[guard] Checking for legacy 'animationId'…"
          if grep -R -nE '\banimationId\b' js/; then
            echo "::error title=Legacy RAF handle found::Rename 'animationId' to 'rafId' and use start()/stopRAF()."
            exit 1
          fi
          echo "[guard] OK: no legacy handle."

          echo "[guard] Verifying new RAF markers…"
          # Use fixed-string grep (-F) so '.' is treated literally
          grep -Fq "let rafId" js/matrix-bg.js || { 
            echo "::error title=Missing marker::Could not find 'let rafId' in js/matrix-bg.js"; exit 1; 
          }
          grep -Fq "VIPSpot._raf" js/matrix-bg.js || { 
            echo "::error title=Missing API::Could not find 'VIPSpot._raf' in js/matrix-bg.js"; exit 1; 
          }
          echo "[guard] OK: new markers present."
      - name: Guard against old email addresses
        shell: bash
        run: |
          set -euo pipefail
          
          echo "[guard] Checking for old email addresses…"
          if grep -R -nE '(franciscoechavez1986@gmail\.com|hello@vipspot\.net)' -- . --exclude-dir=.git --exclude-dir=node_modules --exclude-dir=.github; then
            echo "::error title=Old email addresses found::Replace with contact@vipspot.net"
            exit 1
          fi
          echo "[guard] OK: no old email addresses found."
      - name: Guard against stale backend URLs
        shell: bash
        run: |
          set -euo pipefail
          
          echo "[guard] Ensuring CSP includes current API…"
          grep -q "vipspot-api-a7ce781e1397\.herokuapp\.com" index.html \
            || { echo "::error title=CSP missing current API::connect-src/form-action missing current Heroku app"; exit 1; }
          
          echo "[guard] Checking for stale backend references…"
          if grep -R "vipspot-backend-" index.html js/ 2>/dev/null; then
            echo "::error title=Stale backend host found::Please remove old heroku app name"
            exit 1
          fi
          echo "[guard] OK: no stale backend URLs found."
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
      - run: npm ci || npm i
      - run: npm run build:css
      - name: Start static server (repo root)
        run: |
          python3 -m http.server 8000 & echo $! > server.pid
      - name: Wait for server
        run: |
          for i in {1..60}; do
            curl -fsS http://localhost:8000 >/dev/null && break
            sleep 0.5
          done
      - name: Verify CSP precedes stylesheets
        run: |
          CSP=$(grep -n 'http-equiv="Content-Security-Policy"' index.html | cut -d: -f1 | head -1)
          LINK=$(grep -n '<link[^>]*rel="stylesheet"' index.html | cut -d: -f1 | head -1)
          echo "CSP=$CSP LINK=$LINK"
          test -n "$CSP" && test -n "$LINK" && [ "$CSP" -lt "$LINK" ]
      - name: Prove DOM markers
        run: node scripts/prove-local.mjs
      - name: Stop server
        if: always()
        run: kill $(cat server.pid) || true

  build:
    name: Build static site
    if: github.event_name != 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Guard against problematic Unicode in JS
        run: |
          # Check using Node.js for reliable Unicode detection across platforms
          if node -e "
            const fs=require('fs');
            let found=false;
            for(const f of ['js/main.js','js/matrix-bg.js','js/tilt-tech.js']){
              const s=fs.readFileSync(f,'utf8');
              if(/[\u201C\u201D\u2018\u2019\u2013\u2014\u2026]/.test(s)){
                console.log(f+': Contains problematic Unicode');
                found=true;
              }
            }
            if(found) process.exit(1);
          "; then
            echo "✅ No problematic Unicode characters found in JS files"
          else
            echo "::error title=Problematic Unicode in JS::Replace smart quotes, em-dashes, ellipses with ASCII equivalents."
            exit 1
          fi
      - name: JS syntax validation
        run: |
          for jsfile in js/*.js; do
            echo "Checking syntax: $jsfile"
            node --check "$jsfile" || exit 1
          done
          echo "✅ All JS files have valid syntax"
      - name: API healthcheck
        run: curl -fsS https://vipspot-api-a7ce781e1397.herokuapp.com/healthz
      - name: Guard against legacy RAF handle
        shell: bash
        run: |
          set -euo pipefail

          echo "[guard] Checking for legacy 'animationId'…"
          if grep -R -nE '\banimationId\b' js/; then
            echo "::error title=Legacy RAF handle found::Rename 'animationId' to 'rafId' and use start()/stopRAF()."
            exit 1
          fi
          echo "[guard] OK: no legacy handle."

          echo "[guard] Verifying new RAF markers…"
          # Use fixed-string grep (-F) so '.' is treated literally
          grep -Fq "let rafId" js/matrix-bg.js || { 
            echo "::error title=Missing marker::Could not find 'let rafId' in js/matrix-bg.js"; exit 1; 
          }
          grep -Fq "VIPSpot._raf" js/matrix-bg.js || { 
            echo "::error title=Missing API::Could not find 'VIPSpot._raf' in js/matrix-bg.js"; exit 1; 
          }
          echo "[guard] OK: new markers present."
      - name: Guard against old email addresses
        shell: bash
        run: |
          set -euo pipefail
          
          echo "[guard] Checking for old email addresses…"
          if grep -R -nE '(franciscoechavez1986@gmail\.com|hello@vipspot\.net)' -- . --exclude-dir=.git --exclude-dir=node_modules --exclude-dir=.github; then
            echo "::error title=Old email addresses found::Replace with contact@vipspot.net"
            exit 1
          fi
          echo "[guard] OK: no old email addresses found."
      - name: Guard against stale backend URLs
        shell: bash
        run: |
          set -euo pipefail
          
          echo "[guard] Ensuring CSP includes current API…"
          grep -q "vipspot-api-a7ce781e1397\.herokuapp\.com" index.html \
            || { echo "::error title=CSP missing current API::connect-src/form-action missing current Heroku app"; exit 1; }
          
          echo "[guard] Checking for stale backend references…"
          if grep -R "vipspot-backend-" index.html js/ 2>/dev/null; then
            echo "::error title=Stale backend host found::Please remove old heroku app name"
            exit 1
          fi
          echo "[guard] OK: no stale backend URLs found."
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
      - run: npm ci || npm i
      - run: npm run build:css || echo "no build:css script; continuing"
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: .

  deploy:
    needs: build
    if: github.event_name != 'pull_request'
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4